version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - frontend
        volumes:
            - ../:/var/www/html
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx/
        depends_on:
            - wallet

    wallet:
        build: ./php
        container_name: wallet
        networks:
            - backend
            - frontend
        volumes:
            - ../:/var/www/html
        depends_on:
            - database
        links:
            - database
        env_file:
            ../.env

    database:
        container_name: database
        image: mysql:5.7
        restart: always
        expose:
            - 3306
        ports:
            - "3306:3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=wallet-transfer
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root

networks:
    backend:
    frontend: